# docker-compose.yml
version: '3.7'

services:
  shippy-vessel-service:
    restart: always # ensures the container will restart on crash
    container_name: "shippy-vessel-service"
    build: .
    ports:
      - 50052 # exposing this port on the docker network only, not host
    links:
      - shippy-datastore
    depends_on:
      - shippy-datastore
    networks:
      - shippy-backend-tier
      - shippy-vessel-datastore-tier
    environment:
      DB_HOST: "mongodb://shippy-datastore:27017"
      MICRO_ADDRESS: ":50052"

  shippy-datastore:
    image: mongo:latest
    container_name: "shippy-datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    networks:
      - shippy-vessel-datastore-tier
    ports:
      - 27017
    command: mongod --logpath=/dev/null

networks:
  shippy-vessel-datastore-tier:
    name: shippy-vessel-datastore-tier
  shippy-backend-tier:
    name: shippy-backend-tier
