# docker-compose.yml
version: '3.7'

services:
  shippy-consignment-cli:
    container_name: "shippy-consignment-cli"
    build: ./consignment-cli
    depends_on:
      - shippy-consignment-service
      - shippy-vessel-service
    networks:
      - shippy-backend-tier
    environment:
      MICRO_REGISTRY: "mdns"

  shippy-consignment-service:
    restart: always # ensures the container will restart on crash
    container_name: "shippy-consignment-service"
    build: ./consignment-service
    ports:
      - 50051:50051 # exposing this port on the docker network only, not host
    depends_on:
      - shippy-datastore
    networks:
      - shippy-backend-tier
      - shippy-datastore-tier
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://shippy-datastore:27017"

  shippy-vessel-service:
    restart: always # ensures the container will restart on crash
    container_name: "shippy-vessel-service"
    build: ./vessel-service
    ports:
      - 50052:50051 # exposing this port on the docker network only, not host
    depends_on:
      - shippy-datastore
    networks:
      - shippy-backend-tier
      - shippy-datastore-tier
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://shippy-datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    depends_on:
      - shippy-database
    networks:
      - shippy-backend-tier
      - shippy-datastore-tier
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  shippy-datastore:
    image: mongo:latest
    container_name: "shippy-datastore"
 #   environment:
 #     - MONGO_DATA_DIR=/data/db
 #     - MONGO_LOG_DIR=/dev/null
#    volumes:
#      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 27017:27017
    networks:
      - shippy-datastore-tier
#    command: mongod --logpath=/dev/null

  shippy-database:
    image: postgres
    container_name: "shippy-database"
    ports:
      - 5432:5432
    networks:
      - shippy-datastore-tier
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  shippy-datastore-tier:
    name: shippy-datastore-tier
  shippy-backend-tier:
    name: shippy-backend-tier
