# docker-compose.yml
version: '3.7'

services:
  shippy-consignment-service:
    restart: always # ensures the container will restart on crash
    container_name: "shippy-consignment-service"
    build: .
    ports:
      - 50051 # exposing this port on the docker network only, not host
    links:
      - shippy-datastore
    depends_on:
      - shippy-datastore
    networks:
      - shippy-backend-tier
      - shippy-datastore-tier
    environment:
      DB_HOST: "mongodb://datastore:27017"
      MICRO_ADDRESS: ":50051"

  shippy-datastore:
    image: mongo:latest
    container_name: "shippy-datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    networks:
      - shippy-datastore-tier
    ports:
      - 27017
    command: mongod --logpath=/dev/null

networks:
  shippy-datastore-tier:
    name: shippy-datastore-tier
  shippy-backend-tier:
    name: shippy-backend-tier
